### PR TITLE
Frontend styling changes

### PR DESCRIPTION
**Pull request by renancouto**

### CODE REVIEW

**Comment by yogiben** [comment]
Weird hovering issue: when hover over a menu item, top menu button changes color

image

**Comment by renancouto** [comment]
@yogiben I guess it is inheriting styles from another place. Do you want me to take a look at that?

**Comment by yogiben** [comment]
Would be great if you have time. It just feels a little weird right now.

**Comment by renancouto** [comment]
Sure, no problem.

**Pull request merged**
